# Generated by Django 3.0.6 on 2020-05-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('town', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.TextField()),
                ('age', models.TextField()),
                ('terms', models.BooleanField(default=False)),
            ],
        ),
    ]
