# Generated by Django 3.0.6 on 2020-05-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20200519_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='time',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
