# Generated by Django 3.0.6 on 2020-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='Non_Perishable',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='order',
            name='Perishable',
            field=models.CharField(default='Placeholder', max_length=5000),
        ),
        migrations.AddField(
            model_name='order',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='order',
            name='town',
            field=models.TextField(default='blank'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='blank'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.TextField(default='blank'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.TextField(default='blank'),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgency',
            field=models.TextField(default='blank'),
        ),
    ]
