# Generated by Django 3.0.6 on 2020-05-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0004_order_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alias',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
