# Generated by Django 3.0.6 on 2020-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0006_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donations',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='donation',
            name='number',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='donation',
            name='terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='town',
            field=models.TextField(default='blank'),
        ),
    ]
