# Generated by Django 3.0.6 on 2020-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0008_auto_20200526_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='time',
            field=models.CharField(default='blank', max_length=500),
        ),
    ]
